### ISSUE TITLE
RFE: runtime version detection

### ISSUE THREAD

**Issue by mYmNeo** [seccomp/libseccomp-golang#11]
From #938(https://github.com/opencontainers/runc/issues/938)
There are three variables called verMajor, verMinor, verMicro to identify the version of libseccomp library, but they are fixed after building.If we upgrading the libseccomp library, the binary can not detect the new version.Should we change the detection fix mode to runtime mode such as using pkg --modversion libseccomp

**Comment by pcmoore** [comment]
@mYmNeo I have no idea what to what project #938 refers; I'm going to guess Docker or something similar; for reference please update this with a link to the project/issue.

Regarding the runtime version detection, we probably want to make use of the new seccomp_version() API in the base libseccomp library, we've talked a little about this in PR https://github.com/seccomp/libseccomp-golang/pull/6.

**Comment by mheon** [comment]
The issue with using runtime detection, specifically in the case of Docker, is that it's a new function, and Docker wants to link against a great many versions of the library. Right now, the situation is definitely not ideal (Docker uses the featureset of whatever version of the library it compiles against, which can lead to passing unrecognized constants into the library - like, say, SCMP_ARCH_S390X into a v2.1.1 library which doesn't have the S390 patches). However, if we move to runtime detection, we make the problem worse. We're no longer passing an unknown constant into earlier library versions, and instead we're calling a function that does not exist. Link errors are less desirable than error returns from the library, so in a way it makes things worse. The real solution would be to require that you link against the version of libseccomp you built against, but that's not really an option due to package distribution issues.

Runtime detection of what version of the library we link against is still a desirable thing, and hopefully we'll be able to turn it on in the future. Or maybe we can get Docker in Debian building against the backported v2.2.x library instead of stable v2.1.1, which I believe is most of the justification for requiring linking against many versions.

If this isn't actually a Docker issue, then this will sound very silly indeed, and I apologize!

**Comment by mYmNeo** [comment]
@mheon Yes, this issue is about a sub-project called opencontainers/runc which is related to Docker. I just suffered from the wrong version detection.:disappointed:

**Comment by pcmoore** [comment]
Fixed via e929b20e6658475be1134f17e29d755c676823c6, if you notice any additional problems please re-open this issue.  Thanks!
