### ISSUE TITLE
BUG: version checking does not work for executable linked against the shared library

### ISSUE THREAD

**Issue by dvusboy** [seccomp/libseccomp-golang#20]
For `go` binaries that uses shared library, e.g. `docker-runc`. The version checking really doesn't work. From the look of things, the version is determined at compile time via the header file `seccomp.h`. So, we have a situation where a [published Docker 1.13 RPM](http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_Leap_42.1/x86_64/docker-1.13.0-182.1.x86_64.rpm) probably is built against a version of `libseccomp` that's older than 2.2.1. The result is a run-time error:

> `Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "conditional filtering requires libseccomp version >= 2.2.1`

So the user upgraded `libseccomp` to 2.3 and the error remains. That's because the version check is done against the header values captured at build time. It'd seem that `libseccomp-golang` works correctly only if `libseccomp` is statically linked into the binary.

**Comment by dvusboy** [comment]
I think the check should be made against the values returned by `seccomp_version()` call.

**Comment by mheon** [comment]
That would solve the problem, but would completely remove the ability to use the bindings with `libseccomp` v2.2.x and earlier (as those don't have the `seccomp_version()` call). At present, there are still some major distributions (Debian stable, and it appears Suse as well?) still shipping v2.1.x, so we've held off on this. I agree that it is definitely the way forward, though.

**Comment by dvusboy** [comment]
Thanks for the quick response!

Here's my argument for fixing it now:

[seccomp_internal.go:303](https://github.com/seccomp/libseccomp-golang/blob/master/seccomp_internal.go#L303)

This is the check that's causing me headache. The user cannot resolve it by updating the library because this check will always fail when the binary is built against `libseccomp` v2.1.x. What should've happened is that the maintainers of that RPM should've encountered a compiler error because the function `seccomp_version()` isn't there in the header. Instead, they've successfully produced the RPM and the user encounters a run-time error that cannot be resolved without downgrading Docker. Sure, there's a way to work around the problem, but IMHO, it's more broken than causing compilation errors. Don't you think so?

**Comment by mheon** [comment]
I'd agree that allowing users to compile against a version of the library that produces a defective binary is a worse than forcing a version upgrade. There was some discussion around a minimum version bump in #17 (though that was only to v2.2.x instead of v2.3.0), and I was (and still am) in favor of it. There are a lot of compromises involved in allowing too-low versions of the library - removing a lot of the min version checks would clean things up substantially. I've been otherwise occupied the past few months, but maybe I'll finally throw together a PR for this soon (or you could - contributions certainly welcome!).

I do anticipate there will be some opposition to this from upstream Docker. Requiring Debian build and link against `libseccomp` v2.3.x through a PPA is a big inconvenience and would break a lot of installs on upgrade. Still, that's another matter entirely - there are other users of the bindings besides Docker, and we should be doing the right thing for the general case.

**Comment by dvusboy** [comment]
I can give the PR a try. I can also file an issue with Docker referencing this. There is a workaround of disabling `seccomp` with unconfined access. The alternative would be to statically link the library in their build until they've updated to newer `libseccomp-golang`, which would also force an upgrade to `libseccomp`. Unfortunately, Ubuntu 16.04 is still on 2.2.3. So, yes, it'd be a hard sale. I hope they can do the static linking.

**Comment by mheon** [comment]
Fixed by commit 9814e55a2e59df39b8ad4fbff1226585ebb84674
