### ISSUE TITLE
BUG: Handling of multiple syscall arguments incorrect

### ISSUE THREAD

**Issue by mheon** [seccomp/libseccomp-golang#22]
Issue originally identified at https://github.com/moby/moby/issues/32714

Presently, when adding a rule with multiple syscall arguments, we add each argument separately with a separate call to `seccomp_rule_add_array` and a single syscall specified. This produces an OR relationship between the arguments - IE, we will match if any of the arguments match.

However, using `libseccomp` directly, adding multiple rules at the same time with a single API call will result in an AND relationship - the rule will only match if all of the arguments match.

Matching the behavior of the library is important, and at present use cases requiring ANDing syscall rules are not supported.

**Comment by mheon** [comment]
I'm working on a fix for this, and hope to have it in ASAP

**Comment by mheon** [comment]
Fixed by 06e7a29f36a34b8cf419aeb87b979ee508e58f9e

**Comment by jdstrand** [comment]
Distributions who package snapd but use distribution packaging for the current upstream golang-seccomp release (0.9.0) hit this issue (see https://bugs.launchpad.net/snapd/+bug/1825052). I suggest producing a new release with this fix (eg 0.9.1) so downstreams can more easily pull in the patch.

Since golang-seccomp is meant to be a golang package to facilitate reducing the syscall surface for applications and this bug produces incorrect BPF to achieve that when specifying more that 2 syscall arguments, this probably deserves a CVE assignment so distributions will see the issue and incorporate the fix into their stable releases. I have requested a CVE from MITRE for this issue.

**Comment by mheon** [comment]
I think a 0.9.1 is appropriate to cut, both because of this and the handling for the 2.4.x library series' new features.

**Comment by jdstrand** [comment]
Thanks! And yeah, 2.4.1 is *much* better with arg filtering :)

**Comment by pcmoore** [comment]
@jdstrand thanks!

@mheon if/when a CVE is assigned for this, please make sure this issue is update with the CVE information.  I would suggest adding the CVE number to the issue title and adding a link in the comments. See https://github.com/seccomp/libseccomp/issues/139 as an example.

**Comment by mheon** [comment]
@pcmoore Ack, SGTM

**Comment by jdstrand** [comment]
This is CVE-2017-18367. Reference: https://www.openwall.com/lists/oss-security/2019/04/24/3
